spring.application.name=library
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca_matheus
spring.datasource.username=postgres
spring.datasource.password=matheuseduardo
spring.jpa.hibernate.ddl-auto=update